# /etc/wsl-distribution.conf

[oobe]
command = /usr/lib/wsl/oobe.sh
defaultUid = 1000
defaultName = Archlinux

[shortcut]
enabled = true
icon = /usr/share/icons/default/archlinux.png

[windowsterminal]
enabled = true